services:
  bias-agent:
    build: ./agent-bias
    ports: ["8003:8000"]
    volumes:
      - ./rules.toml:/app/rules.toml
      - ./agent-bias/.env:/app/.env

  eu-ai-act-agent:
    build: ./agent-eu-ai-act
    ports:
      - "8005:8000" # Puerto diferente al bias-agent (8003)
    volumes:
      - ./rules.toml:/app/rules.toml
      - ./agent-eu-ai-act/.env:/app/.env
    restart: unless-stopped

  unesco-agent:
    build: ./agent-unesco
    ports: ["8004:8000"]
    volumes:
      - ./rules.toml:/app/rules.toml
      - ./agent-unesco/.env:/app/.env
